// <auto-generated />
using System;
using GSMAO.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GSMAO.Server.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241127114220_NullDescripcionEN_tableResoluciones")]
    partial class NullDescripcionEN_tableResoluciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivoSAP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Coste")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionEN")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionES")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<int?>("Hse")
                        .HasColumnType("int");

                    b.Property<int>("IdCentroCoste")
                        .HasColumnType("int");

                    b.Property<int>("IdCriticidad")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("IdLocalizacion")
                        .HasColumnType("int");

                    b.Property<int?>("Redundancia")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.Property<int?>("Usabilidad")
                        .HasColumnType("int");

                    b.Property<int>("ValorCriticidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCentroCoste");

                    b.HasIndex("IdCriticidad");

                    b.HasIndex("IdEstadoActivo");

                    b.HasIndex("IdLocalizacion");

                    b.ToTable("Activos");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Activo_Componente", b =>
                {
                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<int>("IdComponente")
                        .HasColumnType("int");

                    b.HasKey("IdActivo", "IdComponente");

                    b.HasIndex("IdComponente");

                    b.ToTable("Activo_Componentes");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Almacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasColumnType("longtext");

                    b.Property<bool>("Externo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.HasKey("Id");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.CentroCoste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CentroCosteSAP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DescripcionEN")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionES")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<int>("IdPlanta")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.HasKey("Id");

                    b.HasIndex("CentroCosteSAP")
                        .IsUnique();

                    b.HasIndex("DescripcionES")
                        .IsUnique();

                    b.HasIndex("IdPlanta");

                    b.ToTable("CentrosDeCostes");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Denominacion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DescripcionEN")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionES")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<int?>("IdComponentePadre")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.HasKey("Id");

                    b.HasIndex("Denominacion")
                        .IsUnique();

                    b.HasIndex("IdComponentePadre");

                    b.ToTable("Componentes");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Criticidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.HasIndex("Siglas")
                        .IsUnique();

                    b.ToTable("Criticidades");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.EstadoActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EstadosActivo");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.EstadoOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EstadosOrden");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.EstadoRepuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EstadosRepuesto");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.EstadoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EstadosUsuario");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.HistorialCambiosUsuarioOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCambio"));

                    b.Property<int>("IdOrden")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioDestino")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IdUsuarioOrigen")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdOrden");

                    b.HasIndex("IdUsuarioDestino");

                    b.HasIndex("IdUsuarioOrigen");

                    b.ToTable("HistorialCambiosUsuariosOrdenes");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEN")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionES")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<int>("IdMecanismoFallo")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.HasKey("Id");

                    b.HasIndex("IdMecanismoFallo");

                    b.HasIndex("DescripcionES", "IdMecanismoFallo")
                        .IsUnique();

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.IncidenciaOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AfectaProduccion")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CambioPieza")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaDeteccion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInsercion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaInsercion"));

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdComponente")
                        .HasColumnType("int");

                    b.Property<int>("IdIncidencia")
                        .HasColumnType("int");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int");

                    b.Property<int?>("IdResolucion")
                        .HasColumnType("int");

                    b.Property<bool>("ParoMaquina")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("IncidenciasOrdenes");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Localizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactoRepuestos")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionEN")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionES")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<int>("IdPlanta")
                        .HasColumnType("int");

                    b.Property<string>("Latitud")
                        .HasColumnType("longtext");

                    b.Property<string>("LocalizacionSAP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Longitud")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.HasKey("Id");

                    b.HasIndex("DescripcionES")
                        .IsUnique();

                    b.HasIndex("IdPlanta");

                    b.HasIndex("LocalizacionSAP")
                        .IsUnique();

                    b.ToTable("Localizaciones");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.MecanismoDeFallo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEN")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionES")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.HasKey("Id");

                    b.HasIndex("DescripcionES")
                        .IsUnique();

                    b.ToTable("MecanismosDeFallo");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComentarioOrden")
                        .HasColumnType("longtext");

                    b.Property<string>("ComentarioResolucion")
                        .HasColumnType("longtext");

                    b.Property<bool>("Confirmada")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoOrden")
                        .HasColumnType("int");

                    b.Property<string>("IdSAP")
                        .HasColumnType("longtext");

                    b.Property<int>("IdTipoOrden")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioCreador")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Materiales")
                        .HasColumnType("longtext");

                    b.Property<float?>("TiempoParada")
                        .HasColumnType("float");

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.HasKey("Id");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdEstadoOrden");

                    b.HasIndex("IdTipoOrden");

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Planta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Latitud")
                        .HasColumnType("longtext");

                    b.Property<string>("Longitud")
                        .HasColumnType("longtext");

                    b.Property<string>("StmpConfig")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("Descripcion", "IdEmpresa")
                        .IsUnique();

                    b.ToTable("Plantas");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEN")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionES")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoRepuesto")
                        .HasColumnType("int");

                    b.Property<float>("Precio")
                        .HasColumnType("float");

                    b.Property<string>("Ref_Albaran")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.HasKey("Id");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdEstadoRepuesto");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Resolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEN")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionES")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.HasKey("Id");

                    b.HasIndex("DescripcionES")
                        .IsUnique();

                    b.ToTable("Resoluciones");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.TipoOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TiposOrden");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<int>("Confirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FechaCreacion"));

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("IdPlanta")
                        .HasColumnType("int");

                    b.Property<string>("IdRol")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UltimaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UltimaModificacion"));

                    b.Property<DateTime?>("UltimoAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime?>("UltimoAcceso"));

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEstadoUsuario");

                    b.HasIndex("IdPlanta");

                    b.HasIndex("IdRol");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Usuario_Orden", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdOrden");

                    b.HasIndex("IdOrden");

                    b.ToTable("Usuarios_Ordenes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Rol", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.ToTable("Roles");

                    b.HasDiscriminator().HasValue("Rol");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Activo", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.CentroCoste", "CentroCoste")
                        .WithMany()
                        .HasForeignKey("IdCentroCoste")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.Criticidad", "Criticidad")
                        .WithMany()
                        .HasForeignKey("IdCriticidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.EstadoActivo", "EstadoActivo")
                        .WithMany()
                        .HasForeignKey("IdEstadoActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.Localizacion", "Localizacion")
                        .WithMany()
                        .HasForeignKey("IdLocalizacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroCoste");

                    b.Navigation("Criticidad");

                    b.Navigation("EstadoActivo");

                    b.Navigation("Localizacion");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Activo_Componente", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("IdComponente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Componente");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.CentroCoste", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Planta", "Planta")
                        .WithMany()
                        .HasForeignKey("IdPlanta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planta");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Componente", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Componente", "ComponentePadre")
                        .WithMany()
                        .HasForeignKey("IdComponentePadre");

                    b.Navigation("ComponentePadre");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.HistorialCambiosUsuarioOrden", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Orden", "Orden")
                        .WithMany()
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDestino");

                    b.HasOne("GSMAO.Server.Database.Tables.Usuario", "UsuarioOrigen")
                        .WithMany()
                        .HasForeignKey("IdUsuarioOrigen");

                    b.Navigation("Orden");

                    b.Navigation("UsuarioDestino");

                    b.Navigation("UsuarioOrigen");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Incidencia", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.MecanismoDeFallo", "MecanismoDeFallo")
                        .WithMany()
                        .HasForeignKey("IdMecanismoFallo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MecanismoDeFallo");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Localizacion", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Planta", "Planta")
                        .WithMany()
                        .HasForeignKey("IdPlanta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planta");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Orden", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.EstadoOrden", "EstadoOrden")
                        .WithMany()
                        .HasForeignKey("IdEstadoOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.TipoOrden", "TipoOrden")
                        .WithMany()
                        .HasForeignKey("IdTipoOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("EstadoOrden");

                    b.Navigation("TipoOrden");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Planta", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Repuesto", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("IdAlmacen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.EstadoRepuesto", "EstadoRepuesto")
                        .WithMany()
                        .HasForeignKey("IdEstadoRepuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("EstadoRepuesto");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Usuario", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa");

                    b.HasOne("GSMAO.Server.Database.Tables.EstadoUsuario", "EstadoUsuario")
                        .WithMany()
                        .HasForeignKey("IdEstadoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.Planta", "Planta")
                        .WithMany()
                        .HasForeignKey("IdPlanta");

                    b.HasOne("GSMAO.Server.Database.Tables.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("EstadoUsuario");

                    b.Navigation("Planta");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GSMAO.Server.Database.Tables.Usuario_Orden", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Orden", "Orden")
                        .WithMany()
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSMAO.Server.Database.Tables.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GSMAO.Server.Database.Tables.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
